name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Hub Image
        run: |
          docker build -t alphadapta/scrap2018papart2:latest .          
          docker push alphadapta/scrap2018papart2:latest
  
  deploy-to-crime-analyst-server:
    needs: build-and-push-to-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: SSH into Droplet, pull image, and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          password: ${{ secrets.DROPLET_SSH_PASSWORD }}
          script: |
            docker pull alphadapta/scrap2018papart2:latest                 
            sh -c 'if docker ps -a -q --filter "name=continerscrap2018papart2" -n 1 | grep -q .; then docker stop continerscrap2018papart2 && docker rm continerscrap2018papart2; fi'                    
            docker run --name continerscrap2018papart2 -p 8032:8032 -d alphadapta/scrap2018papart2:latest
